### PR TITLE
Extract the core functionality to a standalone namespace

### PR DESCRIPTION
**Pull request by vemv**
The `leiningen.how-to-ns` ns (as all plugin ns's) cannot be required from normal Clojure code, even if one places the library in the `:dependencies` vector (as opposed to the `:plugins` one). This is due to the `leiningen.` prefix.

So, this PR moves most of the code to a standalone ns to address that.

Changes:

* Introduced `*exit-fn*`
* Used `[command]` destructuring.

Everything else left untouched!

Tests still pass, and I still can run `lein cljfmt` against itself with comparable results.

Victor

### CODE REVIEW

**Review by gfredericks — CHANGES_REQUESTED** [review]
Thanks!

There's a couple things I would like changed, and then I can merge this:

- Please name the new namespace `com.gfredericks.how-to-ns`
- Instead of adding the `*exit-fn*` feature, keep that functionality in `leiningen.how-to-ns`; you could do this by having the `check` function return a number of problems, and `leiningen.how-to-ns/how-to-ns` could test the return value with `pos?` and call `main/exit` if it passes.

**Comment by vemv** [comment]
Thank you for reviewing!

Feedback implemented

**Comment by gfredericks** [comment]
Looking closer, I don't think this achieves the ideal _I_ had in mind of being close to a leiningen-independent tool (I actually don't even understand what your original problem was; i.e., why a `leiningen` prefix would be a problem).

However, I don't think it's any worse, and is better in some ways, so I'm happy to merge it.

Thanks again!

**Comment by gfredericks** [comment]
Released as `0.1.9`

**Comment by vemv** [comment]
Ace!

As described, the problem was I couldn't `(require 'how-to-ns)`. Actually, I still can't :( Now I get:

```
CompilerException java.io.FileNotFoundException: Could not locate leiningen/core/main__init.class or leiningen/core/main.clj on classpath., compiling:(leiningen/cljfmt.clj:1:1)
```

Let's say I'm set out to fix this and add `[leiningen-core "2.8.1"]` as a dep. Even then:

`(require 'com.gfredericks.how-to-ns)`

will fail with:

```
#error {
 :cause "Cannot open <nil> as a Reader."
 :via
 [{:type clojure.lang.Compiler$CompilerException
   :message "java.lang.IllegalArgumentException: Cannot open <nil> as a Reader., compiling:(classpath.clj:407:35)"
   :at [clojure.lang.Compiler$InvokeExpr eval "Compiler.java" 3700]}
  {:type java.lang.IllegalArgumentException
   :message "Cannot open <nil> as a Reader."
   :at [clojure.java.io$fn__10992 invokeStatic "io.clj" 288]}]
 :trace
 [[clojure.java.io$fn__10992 invokeStatic "io.clj" 288]
   ...
  [leiningen.core.project$eval30410$loading__6434__auto____30411 invoke "project.clj" 1]
```

The problem is the cljfmt dependency, which similarly also was tied to Leiningen.

Fortunately that is in the process of getting fixed: https://github.com/weavejester/cljfmt/pull/123 so when that one is merged, `how-to-ns` would just update its dependency and that would be it.

**Comment by gfredericks** [comment]
Oh that's good to hear. I was worried the cljfmt stuff would make it difficult.

**Pull request merged**
