### PR TITLE
Add basic support for attr-map

### LINKED ISSUE #6: Does not preserve attr-map
It loses the map of attributes between the docstring and the namespace clauses.

If you don't already have a fix for this issue in development, I can provide a patch.

### PR DESCRIPTION
**Pull request by vemv**
Fixes #6

Offers a basic support for attr-map. As with the readerconditionals addition, this is a simple best-effort feature that may not exactly honor the input's original format, or emit a canonically formatted output.

### CODE REVIEW

**Comment by gfredericks** [comment]
Nice, thanks!

**Comment by vemv** [comment]
> Nice, thanks!

🍻

I'll update this PR sometime in the week as I saw a couple points of improvement, especially for maps with more than one entry

**Comment by vemv** [comment]
Ready again

**Comment by gfredericks** [comment]
Released as 0.2.9; thanks again

**Pull request merged**
