### PR TITLE
Add config option to setup tool

### PR DESCRIPTION
**Pull request by velios**
A slightly more voluminous version in terms of changes, which I currently use in my production. We needed a module for extracting configuration from a file to make it easier to use in Docker

almost the same as in the first version, but with some modifications upon practical implementation

the implementation of working with the configuration is almost completely taken from here
https://github.com/weavejester/cljfmt/blob/master/cljfmt/src/cljfmt/config.clj

### CODE REVIEW

**Comment by gfredericks** [comment]
This seems like it's more specific than an OSS clojure library should be. Are there other clojure libraries that have functionality like this?

**Comment by velios** [comment]
By functionality you mean the ability to work with external configuration? I think this makes it easier to use the utility together with Docker or in any other environments that are more complex than local ones where we can control everything.

I mentioned that version 2 may seem like too radical changes to you, but I just wanted to show what I finally got to by implementing your utility in my real project. This looks useful to more than just me, so I brought it up for discussion.

I indicated my source of inspiration several times above, referring to the [cljfmt](https://github.com/weavejester/cljfmt)
 code

**Comment by velios** [comment]
I made a rebase after latest accepted changes. And now you can see that there aren't that many additional changes I'm proposing. And almost all of the proposed code is copied one after another from another, well-tested repository cljfmt.

**Comment by gfredericks** [comment]
Released as `0.2.12`.

**Pull request merged**
